export { useEvents, useEventById, usePublishedEvents, useFeaturedEvents, useCreateEvent, useUpdateEvent, useDeleteEvent, usePublishEvent, useUnpublishEvent } from './useApi'
export { useDashboardAnalytics, useEventAnalytics } from './useApi'
export { useAlbumsByEvent, useAlbumById, useCreateAlbum, useUpdateAlbum, useDeleteAlbum, useReorderAlbums } from './useApi'
export { usePhotosByAlbum, usePhotoById, useUploadPhoto, useUploadPhotos, useUpdatePhotoOrientation, useDeletePhoto, useAllPhotos } from './useApi'
export { useSystemStats, useSystemHealth, useSystemStorage } from './useApi'
export { useSettings, useUpdateSettings, useStudioSettings, useUpdateStudioSettings, useAdminProfile, useUpdateAdminProfile } from './useApi'
export { useModal } from './useModal'
export { useLocalStorage } from './useLocalStorage'

export { useReorderPhotos, useDeletePhotos } from './useApi'
